// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCgLqWnDAcRBYH7ptEFA5UA3hEpJb2FU',
    appId: '1:476116219074:web:94f7d9409c27b58373b75b',
    messagingSenderId: '476116219074',
    projectId: 'to-do-app-8d1b6',
    authDomain: 'to-do-app-8d1b6.firebaseapp.com',
    storageBucket: 'to-do-app-8d1b6.firebasestorage.app',
    measurementId: 'G-MF3ZM1S4FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMtj-T8OyOjM3QKxzvjJFNRIJb3FHTg8',
    appId: '1:476116219074:android:7376582a29a32d0d73b75b',
    messagingSenderId: '476116219074',
    projectId: 'to-do-app-8d1b6',
    storageBucket: 'to-do-app-8d1b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjZqlI6voaK3kJdY87G8EwlBR_E91FR0',
    appId: '1:476116219074:ios:4a62f49095b2143273b75b',
    messagingSenderId: '476116219074',
    projectId: 'to-do-app-8d1b6',
    storageBucket: 'to-do-app-8d1b6.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjZqlI6voaK3kJdY87G8EwlBR_E91FR0',
    appId: '1:476116219074:ios:4a62f49095b2143273b75b',
    messagingSenderId: '476116219074',
    projectId: 'to-do-app-8d1b6',
    storageBucket: 'to-do-app-8d1b6.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );
}
